/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.NutritionistRole;

import Business.WorkQueue.LabTestWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.apache.log4j.Logger;

/**
 *
 * @author Anvita
 */
public class ClinicalAssesmentJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ClinicalAssesmentJPanel
     */
     private JPanel userProcessContainer;
    private LabTestWorkRequest request;
    private static Logger log = Logger.getLogger(ClinicalAssesmentJPanel.class);
    private static final String CLASS_NAME = ClinicalAssesmentJPanel.class.getName();
    public ClinicalAssesmentJPanel(JPanel userProcessContainer, LabTestWorkRequest request) {
        initComponents();
         this.userProcessContainer = userProcessContainer;
        this.request = request;
        patientTxtField.setText(request.getPatientName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabTestLbl = new javax.swing.JLabel();
        patientLbl = new javax.swing.JLabel();
        patientLbl1 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        statusUpdate = new javax.swing.JButton();
        sexcomboBox = new javax.swing.JComboBox<>();
        patientTxtField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabTestLbl.setFont(new java.awt.Font("Nirmala UI", 1, 48)); // NOI18N
        LabTestLbl.setText("Clinical Trial Status");
        add(LabTestLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, -1, -1));

        patientLbl.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        patientLbl.setText("Patient Name");
        add(patientLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, -1, -1));

        patientLbl1.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        patientLbl1.setText("Status");
        patientLbl1.setToolTipText("");
        add(patientLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, -1, -1));

        backBtn.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, -1, -1));

        statusUpdate.setText("Submit");
        statusUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusUpdateActionPerformed(evt);
            }
        });
        add(statusUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 520, -1, -1));

        sexcomboBox.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        sexcomboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Please select--", "Success", "Failure" }));
        add(sexcomboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, -1, -1));

        patientTxtField.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        add(patientTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 140, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void statusUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusUpdateActionPerformed
        // TODO add your handling code here:
        String clinicalStatus = sexcomboBox.getSelectedItem().toString();
        
        if((clinicalStatus == "") || (!clinicalStatus.equalsIgnoreCase("--Please select--"))){
            
            request.getPatient().setClinicStatus(clinicalStatus);
            log.debug("updated patient status to"+" "+request.getPatient().getClinicStatus());
            JOptionPane.showMessageDialog(null, "Status has been updated successfully");
    }
        
        else{
            JOptionPane.showMessageDialog(null, "Please select clincal Status");
            log.error("clinical status has not been selected");
        }
    }//GEN-LAST:event_statusUpdateActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
          userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        NutritionistRequestJPanel dwjp = (NutritionistRequestJPanel) component;
        dwjp.populateRequestTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabTestLbl;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel patientLbl;
    private javax.swing.JLabel patientLbl1;
    private javax.swing.JTextField patientTxtField;
    private javax.swing.JComboBox<String> sexcomboBox;
    private javax.swing.JButton statusUpdate;
    // End of variables declaration//GEN-END:variables
}
