/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package enterprise.ui;

import enterprise.Enterprise;
import enterprise.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author abhilashgp
 */
public class MainScreen extends javax.swing.JPanel {

    /**
     * Creates new form MainScreen
     */
    
    JPanel mainWorkArea;
    UserAccount userAccount;
    Enterprise enterprise;
    
    public MainScreen(JPanel mainWorkArea, UserAccount userAccount) {
        initComponents();
        initComponents();
        this.mainWorkArea = mainWorkArea;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        
        initUsersWorkArea();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        menuPanel = new javax.swing.JPanel();
        mWelcome = new javax.swing.JLabel();
        mLogout = new javax.swing.JButton();
        workSpace = new javax.swing.JPanel();

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        mWelcome.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        mWelcome.setText("<Welcome Message>");

        mLogout.setBackground(new java.awt.Color(153, 153, 153));
        mLogout.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        mLogout.setText("Log Out");
        mLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(mWelcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 511, Short.MAX_VALUE)
                .addComponent(mLogout)
                .addGap(50, 50, 50))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mWelcome)
                    .addComponent(mLogout))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jSplitPane1.setTopComponent(menuPanel);

        workSpace.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(workSpace);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mLogoutActionPerformed
        // TODO add your handling code here:
        mainWorkArea.remove(this);
        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.previous(mainWorkArea);
    }//GEN-LAST:event_mLogoutActionPerformed

    private void initUsersWorkArea() {
        
        mWelcome.setText("Welcome " + ((userAccount.getEmployee() != null) ? userAccount.getEmployee().getName() : userAccount.getUsername()) + "!");
        
        CardLayout layout = (CardLayout) workSpace.getLayout();
        workSpace.add("workArea", userAccount.getRole().createWorkArea(workSpace, userAccount,enterprise));
        layout.next(workSpace);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton mLogout;
    private javax.swing.JLabel mWelcome;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JPanel workSpace;
    // End of variables declaration//GEN-END:variables
}
