/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DishFoodSupplier;

import Business.Dish.DishDirectory;
import Business.Dish.Dish;
import Business.Environment;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.DishFoodOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.apache.log4j.Logger;

/**
 *
 * @author soumya
 */
public class AddDishFoodJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddDishFoodJPanel
     */
    private DishDirectory dishFoodList;
    private JPanel userProcessContainer;
    private Environment business;
    private UserAccount userAccount;
    private DishFoodOrganization dishFoodOrganization;
    private Enterprise enterprise;
    private Network network;
    private static Logger log = Logger.getLogger(AddDishFoodJPanel.class);
    private static final String CLASS_NAME = AddDishFoodJPanel.class.getName();

    public AddDishFoodJPanel(JPanel userProcessContainer, Environment business, UserAccount userAccount, DishFoodOrganization dishFoodOrganization, Enterprise enterprise, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.business = business;
        this.enterprise = enterprise;
        this.network = network;
        this.dishFoodOrganization = dishFoodOrganization;
        populateTable();

    }

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) dishFoodTble.getModel();

        model.setRowCount(0);

        for (Dish d : business.getDishLst().getDishLst()) {

            Object[] row = new Object[2];
            row[0] = d.getDishFoodId();
            row[1] = d;
            model.addRow(row);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        dishFoodTble = new javax.swing.JTable();
        drugtxtField = new javax.swing.JTextField();
        addDishFoodBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        addIngredientButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        processlbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dishFoodTble.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 20)); // NOI18N
        dishFoodTble.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "DishFoodName"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        dishFoodTble.setRowHeight(30);
        jScrollPane1.setViewportView(dishFoodTble);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 141, 720, 270));

        drugtxtField.setFont(new java.awt.Font("Nirmala UI", 1, 20)); // NOI18N
        drugtxtField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        drugtxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drugtxtFieldActionPerformed(evt);
            }
        });
        add(drugtxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 431, 230, 40));

        addDishFoodBtn.setBackground(new java.awt.Color(0, 0, 0));
        addDishFoodBtn.setFont(new java.awt.Font("Nirmala UI", 1, 20)); // NOI18N
        addDishFoodBtn.setForeground(new java.awt.Color(255, 255, 255));
        addDishFoodBtn.setText("Add dishFood");
        addDishFoodBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addDishFoodBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDishFoodBtnActionPerformed(evt);
            }
        });
        add(addDishFoodBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(643, 431, 180, 40));

        jLabel3.setFont(new java.awt.Font("Nirmala UI", 1, 20)); // NOI18N
        jLabel3.setText("DishFood");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 431, 123, 40));

        addIngredientButton.setBackground(new java.awt.Color(0, 0, 0));
        addIngredientButton.setFont(new java.awt.Font("Nirmala UI", 1, 20)); // NOI18N
        addIngredientButton.setForeground(new java.awt.Color(255, 255, 255));
        addIngredientButton.setText("Add Ingredient");
        addIngredientButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addIngredientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addIngredientButtonActionPerformed(evt);
            }
        });
        add(addIngredientButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 500, 180, 40));

        backButton.setFont(new java.awt.Font("Nirmala UI", 1, 20)); // NOI18N
        backButton.setText("BACK");
        backButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 590, 120, 40));

        processlbl.setFont(new java.awt.Font("Nirmala UI", 1, 48)); // NOI18N
        processlbl.setText("Dish Panel");
        add(processlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 300, 70));

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 0, 13)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-dish-64 (1).png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(602, 27, 110, 70));

        jLabel2.setFont(new java.awt.Font("Nirmala UI", 0, 13)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-add-properies-64.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 460, 100, 80));
    }// </editor-fold>//GEN-END:initComponents

    private void drugtxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drugtxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drugtxtFieldActionPerformed

    private void addDishFoodBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDishFoodBtnActionPerformed
        // TODO add your handling code here:

        String dishFoodName = drugtxtField.getText().trim();
        if(dishFoodName.isEmpty())
        {
            JOptionPane.showMessageDialog(null,"DishFood name cannot be empty");
            return;
        }
        ArrayList<String> dishFoodcheck= new ArrayList<>();
        for(Dish d:business.getDishLst().getDishLst())
        {
            dishFoodcheck.add(d.getDishFoodName().toLowerCase());
        }
        if(dishFoodcheck.contains(dishFoodName.toLowerCase()))
        {
            JOptionPane.showMessageDialog(null,"DishFood name already exists");
            return;
        }

        business.getDishLst().addDishLst().setDishFoodName(dishFoodName);
        
        populateTable();
        log.debug(userAccount+" "+"added new ishFood"+" "+dishFoodName);
        drugtxtField.setText("");

    }//GEN-LAST:event_addDishFoodBtnActionPerformed

    private void addIngredientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addIngredientButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = dishFoodTble.getSelectedRow();
        if(selectedRow<0)
        {
            JOptionPane.showMessageDialog(null, "please select a row ");
            return;
        }
        Dish c = (Dish) dishFoodTble.getValueAt(selectedRow, 1);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("AddIngredientsJPanel", new AddIngredientsJPanel(userProcessContainer, business, userAccount, dishFoodOrganization, enterprise, network, c));
        log.debug(userAccount+" "+"entering add ingredients page");
        layout.next(userProcessContainer);
    }//GEN-LAST:event_addIngredientButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDishFoodBtn;
    private javax.swing.JButton addIngredientButton;
    private javax.swing.JButton backButton;
    private javax.swing.JTable dishFoodTble;
    private javax.swing.JTextField drugtxtField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel processlbl;
    // End of variables declaration//GEN-END:variables
}
