/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DishFoodSupplier;

import Business.Environment;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.DishFoodOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.DishWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.apache.log4j.Logger;

/**
 *
 * @author soumya
 */
public class DishFoodSupplierWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form DishFoodSupplierWorkArea
     */
    private JPanel userProcessContainer;
    private Environment business;
    private UserAccount userAccount;
    private DishFoodOrganization dishFoodOrganization;
    private Enterprise enterprise;
    private Network network;
    private static Logger log = Logger.getLogger(DishFoodSupplierWorkArea.class);
    private static final String CLASS_NAME = DishFoodSupplierWorkArea.class.getName();

    public DishFoodSupplierWorkArea(JPanel userProcessContainer, Environment business, UserAccount userAccount, Organization organization, Enterprise enterprise, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.business = business;
        this.enterprise = enterprise;
        this.network = network;
        this.dishFoodOrganization = (DishFoodOrganization) organization;
        log.debug(userAccount+" "+"logged in dishFood work area");
        populateTable();
    }

    public void populateTable() {

        DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();
        model.setRowCount(0);

        for (WorkRequest request : dishFoodOrganization.getWorkQueue().getWorkRequestList()) {
            if (((DishWorkRequest) request).getPatient() == null) {
                Object[] row = new Object[6];
                row[0] = ((DishWorkRequest) request);
                row[1] = ((DishWorkRequest) request).getQuantity();
                row[2] = request.getSender().getEmployee().getEmpName();
                row[3] = request.getReceiver() == null ? null : request.getReceiver().getEmployee().getEmpName();
                row[4] = request.getStatus();
                row[5] = ((DishWorkRequest) request).getDeliveryTime();

                model.addRow(row);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        assignBtn = new javax.swing.JButton();
        reqIngButton = new javax.swing.JButton();
        processBtn = new javax.swing.JButton();
        labRequestButton = new javax.swing.JButton();
        addDishFoodButton = new javax.swing.JButton();
        refreshBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 48)); // NOI18N
        jLabel1.setText("Food Supplier WORK AREA ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 63, -1, 53));

        workRequestJTable.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 20)); // NOI18N
        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DishFood Name", "Quantity", "Sender", "Receiver", "Status", "Delivery Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        workRequestJTable.setRowHeight(30);
        jScrollPane2.setViewportView(workRequestJTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 1240, 290));

        assignBtn.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        assignBtn.setText("Assign to me");
        assignBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        assignBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignBtnActionPerformed(evt);
            }
        });
        add(assignBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 530, 220, -1));

        reqIngButton.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        reqIngButton.setText("request Dish ingredients");
        reqIngButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        reqIngButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reqIngButtonActionPerformed(evt);
            }
        });
        add(reqIngButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 626, -1, 62));

        processBtn.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        processBtn.setText("Process");
        processBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        processBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processBtnActionPerformed(evt);
            }
        });
        add(processBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 530, 230, -1));

        labRequestButton.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        labRequestButton.setText("View Lab Requests");
        labRequestButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labRequestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labRequestButtonActionPerformed(evt);
            }
        });
        add(labRequestButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(518, 636, 300, 50));

        addDishFoodButton.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        addDishFoodButton.setText("ADD DishFood");
        addDishFoodButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addDishFoodButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDishFoodButtonActionPerformed(evt);
            }
        });
        add(addDishFoodButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(928, 636, 220, 50));

        refreshBtn.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        refreshBtn.setText("Refresh");
        refreshBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });
        add(refreshBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 530, 169, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/DrugSupplierWork.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 30, 110, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/SeekPng.com_owner-icon-png_4304156.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 0, 370, 200));
    }// </editor-fold>//GEN-END:initComponents

    private void assignBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = workRequestJTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "please select a row ");
            return;
        }
        //to check whether the the task is already assigned list 
        if (workRequestJTable.getValueAt(selectedRow, 4) != null) {

            if (workRequestJTable.getValueAt(selectedRow, 4).equals("Assigned")) {
                JOptionPane.showMessageDialog(null, "Task is already assigned");
                return;
            }
        }
        //to set the falg if already theere existing job
        int flag = 0;
        for (WorkRequest request : dishFoodOrganization.getWorkQueue().getWorkRequestList()) {

            if (request.getStatus() == null) {
                continue;
            }
            if (request.getStatus().equals("Assigned")) {
                if (request.getReceiver() != null) {
                    if (userAccount.getUsername().equalsIgnoreCase(request.getReceiver().toString())) {
                        flag = 1;
                    }
                }
            }
        }
        if (flag == 1) {
            JOptionPane.showMessageDialog(null, "Please complete the existing request before taking a new request");
            return;

        }
        int flag1 = 0;
        for (WorkRequest request : dishFoodOrganization.getWorkQueue().getWorkRequestList()) {

            if (request.getStatus() == null) {
                continue;
            }
            if (request.getStatus().equals("Processing")) {
                if (request.getReceiver() != null) {
                    if (userAccount.getUsername().equalsIgnoreCase(request.getReceiver().toString())) {
                        flag1 = 1;
                    }
                }
            }
        }
        if (flag1 == 1) {
            JOptionPane.showMessageDialog(null, "Please complete the existing request before taking a new request");
            return;

        }

        WorkRequest request = (WorkRequest) workRequestJTable.getValueAt(selectedRow, 0);
        request.setReceiver(userAccount);
        request.setStatus("Assigned");
        log.debug(userAccount+" "+"assigned himself a task");
        populateTable();
    }//GEN-LAST:event_assignBtnActionPerformed

    private void reqIngButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reqIngButtonActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        log.debug(userAccount+" "+"entering ingredient requests page");
        userProcessContainer.add("ViewIngredientRequestJPanel", new ViewIngredientRequestsJPanel(userProcessContainer, userAccount, enterprise, dishFoodOrganization, network));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_reqIngButtonActionPerformed

    private void processBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = workRequestJTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "please select a row");
            return;
        }

        DishWorkRequest request = (DishWorkRequest) workRequestJTable.getValueAt(selectedRow, 0);
        if (workRequestJTable.getValueAt(selectedRow, 4) == null) {
            JOptionPane.showMessageDialog(null, "Task is not assigned to you for process");
            return;
        }
        int flag = 0;

        if (workRequestJTable.getValueAt(selectedRow, 4).equals("Processing") && userAccount.getUsername().equalsIgnoreCase(request.getReceiver().toString())) {

            flag = 1;
        }
        if (flag != 1) {
            if (workRequestJTable.getValueAt(selectedRow, 4) != null) {

                if (!(((workRequestJTable.getValueAt(selectedRow, 4).equals("Assigned"))) && (userAccount.getUsername().equalsIgnoreCase(request.getReceiver().toString())))) {
                    JOptionPane.showMessageDialog(null, "Task is not assigned to you for process");
                    return;
                }
            }
        }

        request.setStatus("Processing");

        ProcessDishFoodWorkRequest processWorkRequestJPanel = new ProcessDishFoodWorkRequest(userProcessContainer, request);
        userProcessContainer.add("processWorkRequestJPanel", processWorkRequestJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        log.debug(userAccount+" "+"entering processing page");
        layout.next(userProcessContainer);
    }//GEN-LAST:event_processBtnActionPerformed

    private void labRequestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labRequestButtonActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        log.debug(userAccount+" "+"entering lab requests page");
        userProcessContainer.add("LabResultsJPanel", new LabResultsJpanel(userProcessContainer, userAccount, enterprise, dishFoodOrganization, network, business));
        layout.next(userProcessContainer);

    }//GEN-LAST:event_labRequestButtonActionPerformed

    private void addDishFoodButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDishFoodButtonActionPerformed
        // TODO add your handling code here:

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        log.debug(userAccount+" "+"entering dishFood adding page");
        userProcessContainer.add("AddDishFoodJPanel", new AddDishFoodJPanel(userProcessContainer, business, userAccount, dishFoodOrganization, enterprise, network));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_addDishFoodButtonActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_refreshBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDishFoodButton;
    private javax.swing.JButton assignBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton labRequestButton;
    private javax.swing.JButton processBtn;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JButton reqIngButton;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
