/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DishFoodSupplier;

import Business.Ingredient.Ingredient;
import Business.Environment;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.DishFoodOrganization;
import static Business.Organization.Organization.Type.DishFood;
import Business.UserAccount.UserAccount;
import javax.swing.JPanel;
import Business.Dish.Dish;
import Business.Allergin.Allergin;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.table.DefaultTableModel;
import org.apache.log4j.Logger;

/**
 *
 * @author soumya
 */
public class ExistingDishFoodResultsJpanel extends javax.swing.JPanel {

    /**
     * Creates new form ExistingDishFoodResultsJpanel
     */
    private JPanel userProcessContainer;
    private Environment business;
    private UserAccount userAccount;
    private DishFoodOrganization dishFoodOrganization ;
    private Enterprise enterprise;
    private Network network;
    private Dish dish;
    private static Logger log = Logger.getLogger(ExistingDishFoodResultsJpanel.class);
    private static final String CLASS_NAME = ExistingDishFoodResultsJpanel.class.getName();
    public ExistingDishFoodResultsJpanel(JPanel userProcessContainer,UserAccount userAccount,Enterprise enterprise, DishFoodOrganization dishFoodOrganization,Network network,Dish dish) {
        initComponents();
         this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.dishFoodOrganization = dishFoodOrganization;
        this.enterprise = enterprise;
        this.network = network;
        this.dish=dish;
        populateTable();
        dishFoodnametxt.setText(dish.getDishFoodName());
        
    }
    
    public void populateTable(){
         DefaultTableModel model = (DefaultTableModel)ingredientAllerginTbl.getModel();
        
        model.setRowCount(0);
        Object[] row = new Object[2];
        int i = 0;
            for(Ingredient c : dish.getIngredientLst().getIngLst()){
                 
                 row[0] = c.getIngName();
                 
                    
                    Allergin g=  dish.getAllergenRecord().getAllerginRecord().get(i);
                      
                      row[1] = g.getAllerginName();
                      model.addRow(row);
                     i++;
                 }
                 
            
         
        
         
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ingredientAllerginTbl = new javax.swing.JTable();
        dishFoodnametxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ingredientAllerginTbl.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 20)); // NOI18N
        ingredientAllerginTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IngredientName", "AllerginName"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ingredientAllerginTbl.setRowHeight(30);
        ingredientAllerginTbl.getTableHeader().setResizingAllowed(false);
        ingredientAllerginTbl.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(ingredientAllerginTbl);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 630, 150));

        dishFoodnametxt.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        dishFoodnametxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dishFoodnametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dishFoodnametxtActionPerformed(evt);
            }
        });
        add(dishFoodnametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 183, 290, -1));

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jLabel1.setText("DishFood Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 186, 210, -1));

        backBtn.setBackground(new java.awt.Color(0, 0, 0));
        backBtn.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("BACK");
        backBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 540, 130, 33));

        jLabel3.setFont(new java.awt.Font("Nirmala UI", 1, 48)); // NOI18N
        jLabel3.setText("Existing DishFood");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 420, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-hamper-48.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(692, 47, 150, 90));
    }// </editor-fold>//GEN-END:initComponents

    private void dishFoodnametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dishFoodnametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dishFoodnametxtActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        LabResultsJpanel lrjp = (LabResultsJpanel) component;
        lrjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField dishFoodnametxt;
    private javax.swing.JTable ingredientAllerginTbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
