/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DishFoodSupplier;

import Business.IngredientCatalogue.Ingridient;
import Business.Enterprise.Enterprise;
import Business.DishFoodCatalogue.DishFoodCatalogue;
import Business.DishFoodCatalogue.DishFoodCatalogueDirectory;
import Business.Organization.DishFoodOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.apache.log4j.Logger;
import userinterface.CateringRole.CateringWorkArea;

/**
 *
 * @author abhilashgp
 */
public class ViewIngredientDetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewIngredientDetailsJPanel
     */
    JPanel userProcessContainer;
    private UserAccount userAccount;
    private Enterprise enterprise;
    private DishFoodCatalogueDirectory d;
    private DishFoodOrganization dishFoodOrg;
    private Ingridient di;
    private static Logger log = Logger.getLogger(ViewIngredientDetailsJPanel.class);
    private static final String CLASS_NAME = ViewIngredientDetailsJPanel.class.getName();
    public ViewIngredientDetailsJPanel(JPanel userProcessContainer, UserAccount userAccount, Enterprise enterprise,Ingridient mi) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.userAccount=userAccount;
        this.enterprise=enterprise;
        this.dishFoodOrg= dishFoodOrg;
        this.di=mi;
       
            
        serialNumTextField.setText(String.valueOf(mi.getSerialNumber()));
        availQuantityTextField.setText(String.valueOf(mi.getAvailableQuantity()));
        ingredientNameTextField.setText(mi.getIngriName());
        saveButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        serialNumLabel = new javax.swing.JLabel();
        serialNumTextField = new javax.swing.JTextField();
        dishFoodLabel = new javax.swing.JLabel();
        ingredientNameTextField = new javax.swing.JTextField();
        availLabel = new javax.swing.JLabel();
        availQuantityTextField = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(230, 224, 224));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        serialNumLabel.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        serialNumLabel.setText("SERIAL NUMBER:");
        add(serialNumLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, -1, 30));

        serialNumTextField.setEditable(false);
        serialNumTextField.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 20)); // NOI18N
        serialNumTextField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(serialNumTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 171, 207, -1));

        dishFoodLabel.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        dishFoodLabel.setText("Ingredient Name:");
        add(dishFoodLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, -1, 30));

        ingredientNameTextField.setEditable(false);
        ingredientNameTextField.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 20)); // NOI18N
        ingredientNameTextField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(ingredientNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 271, 207, -1));

        availLabel.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        availLabel.setText("Availability:");
        add(availLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, -1, 30));

        availQuantityTextField.setEditable(false);
        availQuantityTextField.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 20)); // NOI18N
        availQuantityTextField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        availQuantityTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availQuantityTextFieldActionPerformed(evt);
            }
        });
        add(availQuantityTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 367, 207, -1));

        backButton.setBackground(new java.awt.Color(0, 0, 0));
        backButton.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText(" BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 490, 190, -1));

        saveButton.setBackground(new java.awt.Color(0, 0, 0));
        saveButton.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        saveButton.setForeground(new java.awt.Color(255, 255, 255));
        saveButton.setText("SAVE");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 490, 136, -1));

        updateButton.setBackground(new java.awt.Color(0, 0, 0));
        updateButton.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        updateButton.setForeground(new java.awt.Color(255, 255, 255));
        updateButton.setText("UPDATE");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(599, 490, 136, -1));

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 48)); // NOI18N
        jLabel1.setText("Ingredients Details");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, -1, 53));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Pictures\\Images\\icons8-ingredients-100.png")); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 40, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void availQuantityTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availQuantityTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_availQuantityTextFieldActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ViewIngredientRequestsJPanel me = (ViewIngredientRequestsJPanel) component;
        me.reorderTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        if(ingredientNameTextField.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "chemical name is empty");
            return;
        }
        di.setIngriName(ingredientNameTextField.getText());
        
        try{
        int availableQuantity= Integer.parseInt(availQuantityTextField.getText());
        di.setAvailableQuantity(availableQuantity);
        }
        catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(null, "Available quantity must be integer");
            return;
        }
        try{
        int serialNumber= Integer.parseInt(serialNumTextField.getText());
        di.setSerialNumber(serialNumber);
        }
         catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(null, "Serial number must be integer");
            return;
        }
        
        saveButton.setEnabled(false);
        updateButton.setEnabled(true);
        ingredientNameTextField.setEditable(false);
        serialNumTextField.setEditable(false);
        availQuantityTextField.setEditable(false);

        JOptionPane.showMessageDialog(null, "Dish updated Successfully", "Warning", JOptionPane.INFORMATION_MESSAGE);
        log.debug(userAccount+" "+"updated ingredients details successfully");
    }//GEN-LAST:event_saveButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed

        ingredientNameTextField.setEditable(true);
        serialNumTextField.setEditable(true);
        availQuantityTextField.setEditable(true);
        updateButton.setEnabled(false);
        saveButton.setEnabled(true);
    }//GEN-LAST:event_updateButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel availLabel;
    private javax.swing.JTextField availQuantityTextField;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel dishFoodLabel;
    private javax.swing.JTextField ingredientNameTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel serialNumLabel;
    private javax.swing.JTextField serialNumTextField;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
