/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DishFoodSupplier;

/**
 *
 * @author abhilashgp
 */
public class ViewLabTestResultsJapnel extends javax.swing.JPanel {

    /**
     * Creates new form ViewLabTestResultsJapnel
     */
    public ViewLabTestResultsJapnel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        patientTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        allerginTbl = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(230, 224, 224));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        patientTextField.setFont(new java.awt.Font("Nirmala UI", 0, 22)); // NOI18N
        patientTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        patientTextField.setEnabled(false);
        add(patientTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 240, 180, -1));

        allerginTbl.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 20)); // NOI18N
        allerginTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Allergin"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        allerginTbl.setRowHeight(30);
        allerginTbl.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(allerginTbl);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 317, -1, 200));

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 48)); // NOI18N
        jLabel1.setText(" LAB TEST RESULTS");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 480, 52));

        jLabel2.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jLabel2.setText("Patient Name :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 200, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Pictures\\Images\\icons8-lab-coat-100.png")); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 50, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable allerginTbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField patientTextField;
    // End of variables declaration//GEN-END:variables
}
