/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CateringRole;

import Business.Enterprise.Enterprise;
import Business.DishFoodCatalogue.DishFoodCatalogue;
import Business.DishFoodCatalogue.DishFoodCatalogueDirectory;
import Business.Organization.Organization;
import Business.Organization.CateringOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.apache.log4j.Logger;

/**
 *
 * @author soumya
 */
public class ViewDetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewDetailsJPanel
     */
    JPanel userProcessContainer;
    private UserAccount userAccount;
    private Enterprise enterprise;
    private DishFoodCatalogueDirectory fc;
    private Organization org;
    private CateringOrganization caterorg;
    private DishFoodCatalogue dfc;
    private static Logger log = Logger.getLogger(ViewDetailsJPanel.class);
    private static final String CLASS_NAME = ViewDetailsJPanel.class.getName();

    public ViewDetailsJPanel(JPanel userProcessContainer, UserAccount userAccount, Enterprise enterprise, DishFoodCatalogue dfc) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.caterorg = caterorg;
        this.dfc = dfc;

        serialNumTxtField.setText(String.valueOf(dfc.getSerialNumber()));
        availQuantityTxtField.setText(String.valueOf(dfc.getAvailableQuantity()));
        DishFoodNameTxtField.setText(dfc.getDishFoodName());
        saveButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        serialNumLbl = new javax.swing.JLabel();
        serialNumTxtField = new javax.swing.JTextField();
        dishFoodLbl = new javax.swing.JLabel();
        DishFoodNameTxtField = new javax.swing.JTextField();
        availLbl = new javax.swing.JLabel();
        availQuantityTxtField = new javax.swing.JTextField();
        updateButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        dishLbl = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        serialNumLbl.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        serialNumLbl.setText("SERIAL NUMBER:");
        add(serialNumLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 281, -1, 30));

        serialNumTxtField.setEditable(false);
        serialNumTxtField.setBackground(new java.awt.Color(255, 255, 255));
        serialNumTxtField.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        serialNumTxtField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(serialNumTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 283, 207, -1));

        dishFoodLbl.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        dishFoodLbl.setText("DishFood Name:");
        add(dishFoodLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 379, -1, 30));

        DishFoodNameTxtField.setEditable(false);
        DishFoodNameTxtField.setBackground(new java.awt.Color(255, 255, 255));
        DishFoodNameTxtField.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        DishFoodNameTxtField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(DishFoodNameTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 383, 207, -1));

        availLbl.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        availLbl.setText("Availability:");
        add(availLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 476, -1, 30));

        availQuantityTxtField.setEditable(false);
        availQuantityTxtField.setBackground(new java.awt.Color(255, 255, 255));
        availQuantityTxtField.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        availQuantityTxtField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        availQuantityTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availQuantityTxtFieldActionPerformed(evt);
            }
        });
        add(availQuantityTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 479, 207, -1));

        updateButton.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        updateButton.setText("UPDATE");
        updateButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 580, 136, -1));

        saveButton.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        saveButton.setText("SAVE");
        saveButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 580, 130, -1));

        backButton.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        backButton.setText("BACK");
        backButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 580, 110, -1));

        dishLbl.setFont(new java.awt.Font("Nirmala UI", 1, 48)); // NOI18N
        dishLbl.setText("View Dish Details");
        add(dishLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-dish-85.png"))); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 70, 130, 90));
    }// </editor-fold>//GEN-END:initComponents

    private void availQuantityTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availQuantityTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_availQuantityTxtFieldActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed

        DishFoodNameTxtField.setEditable(true);
        serialNumTxtField.setEditable(true);
        availQuantityTxtField.setEditable(true);
        updateButton.setEnabled(false);
        saveButton.setEnabled(true);

    }//GEN-LAST:event_updateButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        
        if(DishFoodNameTxtField.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"enter a valid Dish name");
            return;
        }
        dfc.setDishFoodName(DishFoodNameTxtField.getText());
        try{
        int availableQuantity = Integer.parseInt(availQuantityTxtField.getText());
          dfc.setAvailableQuantity(availableQuantity);
        }
        catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "serial number must be integer!");
            return;
        }
      try
      {
        int serialNumber = Integer.parseInt(serialNumTxtField.getText());
        dfc.setSerialNumber(serialNumber);
      }
      catch(NumberFormatException e)
      {
          JOptionPane.showMessageDialog(null, "serial number must be integer!");
          return;
      }
        
        DishFoodNameTxtField.setEditable(false);
        serialNumTxtField.setEditable(false);
        availQuantityTxtField.setEditable(false);
        saveButton.setEnabled(false);
        updateButton.setEnabled(true);
        log.debug(userAccount+" "+" Dish details updates");

        JOptionPane.showMessageDialog(null, "Dish updated", "Warning", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_saveButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CateringWorkArea me = (CateringWorkArea) component;
        me.reorderTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DishFoodNameTxtField;
    private javax.swing.JLabel availLbl;
    private javax.swing.JTextField availQuantityTxtField;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel dishFoodLbl;
    private javax.swing.JLabel dishLbl;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel serialNumLbl;
    private javax.swing.JTextField serialNumTxtField;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
